builds:
  - binary: meta
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archive:
  format: binary
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - VERSION
